version: "3.8"
   
services:
  flask-app:
    build:
      context: .  
    ports:
      - "5000:5000"  
    depends_on:
      - db
      - rabbit
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DB_HOST=db
    command: flask run -h 0.0.0.0  
    links:
      - db
    networks:
      - default
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=conversor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  rabbit:
    image: rabbitmq:3.7.5-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
    command: sh -c "rabbitmq-plugins enable rabbitmq_management;  echo '[{rabbit, [{loopback_users, []}]}].' > /etc/rabbitmq/rabbitmq.config; rabbitmq-server"
